apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: miservicio-apache
        image: yungel1/apache_kubernetes_as:latest
        ports:
        - containerPort: 80