version: "3.9"
services:
  miservicio_mysql:
   image: mysql:8
   environment:
    - MYSQL_DATABASE=home
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=username
    - MYSQL_PASSWORD=password
   volumes:
   # Montamos un volumen para MySQL para no perder los datos de bd
    - ./mysql/volumenes:/var/lib/mysql  
   # Sentencias SQL a ejecutar  
    - ./mysql/scripts:/docker-entrypoint-initdb.d
   ports:
    - 3306:3306
   restart: always
   
  miservicio_apache:
   build: ./apache
   volumes:
   # Montamos nuestra web desde fuera en el directorio web del contenedor
    - ./apache/miweb/:/var/www/html/
   ports:
    - 80:80
   links: 
    - miservicio_mysql
volumes:
 volumenes:
 scripts:
 miweb:
